import type { VercelRequest, VercelResponse } from '@vercel/node'

export default function handler(req: VercelRequest, res: VercelResponse) {
  return res.json({
    "scrollName": "Lorem Ipsum",
    "thumbnailUrl": "https://i2.wp.com/bakingmischief.com/wp-content/uploads/2016/09/kettle-corn-image-square-3-200x200.jpg",
    "backgroundUrl": "https://i.imgur.com/Gd414OJ.jpg",
    "images": [
      null,
      null, 
      null,
      "https://images.wallpapersden.com/image/download/the-luminous-realm-hd-fantasy-forest_bmVpZm2UmZqaraWkpJRmbmdlrWZlbWU.jpg",
      "https://images.wallpapersden.com/image/download/the-luminous-realm-hd-fantasy-forest_bmVpZm2UmZqaraWkpJRmbmdlrWZlbWU.jpg",
      "https://images.wallpapersden.com/image/download/red-roses-with-snowy-mountains-hd-fantasy-landscape_bmVrZmiUmZqaraWkpJRmbmdlrWZlbWU.jpg",
      null,
    ],
    "text": [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Fusce id velit ut tortor. Quis lectus nulla at volutpat diam ut venenatis tellus in. Magna eget est lorem ipsum dolor. Mattis vulputate enim nulla aliquet porttitor lacus luctus. Aliquet risus feugiat in ante metus dictum at tempor commodo. Sed felis eget velit aliquet sagittis id consectetur purus ut. Euismod in pellentesque massa placerat duis ultricies lacus. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Purus gravida quis blandit turpis cursus in.",
      "Pharetra sit amet aliquam id. A iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Tellus in hac habitasse platea. Tellus in hac habitasse platea dictumst vestibulum. Vitae justo eget magna fermentum iaculis eu. Maecenas accumsan lacus vel facilisis volutpat. In eu mi bibendum neque egestas congue quisque egestas. Donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Varius duis at consectetur lorem donec massa sapien faucibus. Aliquet risus feugiat in ante metus dictum at. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Mi quis hendrerit dolor magna eget est. Sit amet dictum sit amet justo donec enim. Amet dictum sit amet justo donec enim diam vulputate. Vel turpis nunc eget lorem dolor sed viverra ipsum nunc.",
      "Lectus urna duis convallis convallis tellus. Mattis pellentesque id nibh tortor id aliquet lectus proin. Sapien pellentesque habitant morbi tristique senectus et netus et malesuada. Amet consectetur adipiscing elit pellentesque. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Posuere urna nec tincidunt praesent semper feugiat nibh sed pulvinar. In cursus turpis massa tincidunt dui. Arcu non sodales neque sodales ut etiam sit amet. Diam quam nulla porttitor massa id neque aliquam. Quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus. Sodales ut eu sem integer. Ultricies integer quis auctor elit.",
      "The image appears here. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Risus sed vulputate odio ut enim blandit. Aliquam purus sit amet luctus venenatis lectus magna fringilla. Cras pulvinar mattis nunc sed blandit libero volutpat sed cras. Dui sapien eget mi proin sed. Diam donec adipiscing tristique risus nec feugiat. Ut etiam sit amet nisl. Ac auctor augue mauris augue neque. Mauris a diam maecenas sed enim. Ipsum dolor sit amet consectetur adipiscing. Risus commodo viverra maecenas accumsan. Fusce ut placerat orci nulla pellentesque dignissim. Nunc eget lorem dolor sed viverra ipsum nunc aliquet. Ornare lectus sit amet est placerat in egestas erat. Leo integer malesuada nunc vel risus commodo viverra maecenas. Enim lobortis scelerisque fermentum dui faucibus. Et netus et malesuada fames. Rhoncus dolor purus non enim. Risus pretium quam vulputate dignissim suspendisse in est.",
      "Same image stays. Enim eu turpis egestas pretium aenean. Dolor magna eget est lorem ipsum. Enim sit amet venenatis urna cursus eget nunc scelerisque viverra. Sit amet nisl suscipit adipiscing bibendum est ultricies integer. Pretium aenean pharetra magna ac placerat vestibulum lectus. Pellentesque sit amet porttitor eget dolor. Integer malesuada nunc vel risus commodo viverra. Mauris augue neque gravida in fermentum et sollicitudin ac. Habitant morbi tristique senectus et netus et malesuada fames. Velit egestas dui id ornare arcu odio ut. Et malesuada fames ac turpis egestas maecenas. At varius vel pharetra vel turpis. Dolor purus non enim praesent elementum facilisis leo vel fringilla. Quam quisque id diam vel quam elementum pulvinar etiam. Mattis ullamcorper velit sed ullamcorper morbi tincidunt. Justo laoreet sit amet cursus sit. Est velit egestas dui id ornare arcu odio ut sem.",
      "New image is shown. Ante metus dictum at tempor. Vel facilisis volutpat est velit egestas dui id ornare. Ut etiam sit amet nisl purus in mollis nunc. Amet nisl purus in mollis nunc sed. Pretium quam vulputate dignissim suspendisse in est. Blandit cursus risus at ultrices mi tempus imperdiet nulla malesuada. Id interdum velit laoreet id donec ultrices tincidunt arcu. Id ornare arcu odio ut sem nulla pharetra diam sit. Facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Posuere morbi leo urna molestie at elementum eu facilisis. Elementum pulvinar etiam non quam. Felis donec et odio pellentesque diam volutpat commodo sed. Dignissim enim sit amet venenatis urna.",
      "image disappears. Tellus integer feugiat scelerisque varius. Consectetur adipiscing elit duis tristique sollicitudin nibh. Penatibus et magnis dis parturient montes nascetur ridiculus mus mauris. Sociis natoque penatibus et magnis. Senectus et netus et malesuada. Vitae tortor condimentum lacinia quis. Est lorem ipsum dolor sit amet consectetur adipiscing elit. Id eu nisl nunc mi ipsum faucibus vitae aliquet. Vel pharetra vel turpis nunc eget. Auctor eu augue ut lectus arcu. Volutpat sed cras ornare arcu."
    ]
  })
}
